### PR TITLE
Feature/proc mem used

### PR DESCRIPTION
**Pull request by tnguyenns1**

### CODE REVIEW

**Review by denizen378-zz — APPROVED** [review]
👍 looks great

**Comment by CheRuisiBesares** [comment]
I like this plan. It does seem like it makes more sense to do the math on the edges. I was talking with @denizen378 about this a little this am. I think one of the things that we should probably talk about at some point is how to pull out single metrics from each of these collectors since we are only using a subset of these metrics. So along the lines of what @supernomad was talking about while yall were asleep the other day. Anyway convo for another time this looks simple and gets this done i love it.

**Comment by tnguyenns1** [comment]
@CheRuisiBesares yeah, I second that. 
Ideally we should only send those metrics that our monitoring/alerting system want to have. I guess it takes a little effort to decide which is needed, which is not, but no pain no gain.

Speaking for this PR, if you guys have no problem with this approach, I'm gonna merge this and land this tomorrow. @nsone/devops

**Comment by supernomad** [comment]
I think its fine to add metrics for now until we have some time to actually audit things and figure out what we want to do generally. :rocket:

**Review by supernomad — APPROVED** [review]

**Pull request merged**
